#sudo: required
services:
  - docker


before_install:
  - docker build -t mymobantz/docker-react -f Dockerfile.dev .


script:

  - docker run mymobantz/docker-react npm run test -- --coverage
  - bash build.sh || travis_terminate 1;
